name: flutter_menu_list
description: simple flutter menu list.
version: 0.0.1
author: naoki0719
homepage: https://github.com/naoki0719/flutter_menu_list

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: 1.8.0+1

flutter:
